# Generated by Django 2.1.4 on 2018-12-16 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('codename', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.BooleanField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.BooleanField()),
                ('is_active', models.BooleanField()),
                ('date_joined', models.DateTimeField()),
                ('last_name', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('change_message', models.TextField()),
                ('action_flag', models.PositiveSmallIntegerField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(blank=True, db_column='YEAR', null=True)),
                ('day', models.TextField(blank=True, db_column='DAY', null=True)),
                ('date', models.TextField(blank=True, db_column='DATE', null=True)),
                ('time', models.TextField(blank=True, db_column='TIME', null=True)),
                ('artist', models.TextField(blank=True, db_column='ARTIST', null=True)),
                ('appearing_with', models.TextField(blank=True, db_column='APPEARING_WITH', null=True)),
                ('venue', models.TextField(blank=True, db_column='VENUE', null=True)),
                ('price_student', models.TextField(blank=True, db_column='PRICE_Student', null=True)),
                ('price_public', models.TextField(blank=True, db_column='PRICE_public', null=True)),
                ('cp_nl_ad', models.TextField(blank=True, db_column='CP_NL_AD', null=True)),
                ('page', models.TextField(blank=True, db_column='PAGE', null=True)),
                ('cp_rev', models.TextField(blank=True, db_column='CP_REV', null=True)),
                ('page_1', models.TextField(blank=True, db_column='PAGE_1', null=True)),
                ('cp_preview', models.TextField(blank=True, db_column='CP_PREVIEW', null=True)),
                ('page_2', models.TextField(blank=True, db_column='PAGE_2', null=True)),
                ('cp_letters_1', models.TextField(blank=True, db_column='CP_LETTERS_1', null=True)),
                ('page_3', models.TextField(blank=True, db_column='PAGE_3', null=True)),
                ('cp_letters_2', models.TextField(blank=True, db_column='CP_LETTERS_2', null=True)),
                ('page_4', models.TextField(blank=True, db_column='PAGE_4', null=True)),
                ('cp_letters_3', models.TextField(blank=True, db_column='CP_LETTERS_3', null=True)),
                ('page_5', models.TextField(blank=True, db_column='PAGE_5', null=True)),
                ('cp_eds', models.TextField(blank=True, db_column='CP_EDS', null=True)),
                ('page_6', models.TextField(blank=True, db_column='PAGE_6', null=True)),
                ('yrbk', models.TextField(blank=True, db_column='YRBK', null=True)),
                ('page_7', models.TextField(blank=True, db_column='PAGE_7', null=True)),
                ('pr_article', models.TextField(blank=True, db_column='PR_ARTICLE', null=True)),
                ('pr_page', models.TextField(blank=True, db_column='PR_PAGE', null=True)),
                ('beekman_st', models.TextField(blank=True, db_column='BEEKMAN_ST', null=True)),
                ('beek_st_pg', models.TextField(blank=True, db_column='BEEK_ST_PG', null=True)),
                ('weekly', models.TextField(blank=True, db_column='WEEKLY', null=True)),
                ('wkly_pg', models.TextField(blank=True, db_column='WKLY_PG', null=True)),
                ('verification', models.TextField(blank=True, db_column='VERIFICATION', null=True)),
                ('sa_box', models.TextField(blank=True, db_column='SA_BOX', null=True)),
                ('file', models.TextField(blank=True, db_column='FILE', null=True)),
                ('flat_fee', models.TextField(blank=True, db_column='FLAT_FEE', null=True)),
                ('light_sound', models.TextField(blank=True, db_column='LIGHT_SOUND', null=True)),
                ('percentage', models.TextField(blank=True, db_column='PERCENTAGE', null=True)),
                ('other_fee', models.TextField(blank=True, db_column='OTHER_FEE', null=True)),
                ('total_cost', models.TextField(blank=True, db_column='TOTAL_COST', null=True)),
                ('speaker', models.TextField(blank=True, db_column='SPEAKER', null=True)),
                ('notes_1', models.TextField(blank=True, db_column='NOTES_1', null=True)),
                ('notes_2', models.TextField(blank=True, db_column='NOTES_2', null=True)),
                ('notes_3', models.TextField(blank=True, db_column='NOTES_3', null=True)),
                ('notes_4', models.TextField(blank=True, db_column='NOTES_4', null=True)),
                ('notes_5', models.TextField(blank=True, db_column='NOTES_5', null=True)),
                ('column45', models.TextField(blank=True, db_column='Column45', null=True)),
            ],
            options={
                'db_table': 'EVENTS',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FieldTags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('column', models.TextField(blank=True, db_column='COLUMN', null=True)),
                ('field_tag', models.TextField(blank=True, db_column='FIELD_TAG', null=True)),
                ('description', models.TextField(blank=True, db_column='DESCRIPTION', null=True)),
            ],
            options={
                'db_table': 'FIELD TAGS',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sheet3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(blank=True, db_column='YEAR', null=True)),
                ('sa_budget', models.TextField(blank=True, db_column='SA_BUDGET', null=True)),
                ('acb_budget', models.TextField(blank=True, db_column='ACB_BUDGET', null=True)),
                ('concert_budget', models.TextField(blank=True, db_column='CONCERT_BUDGET', null=True)),
                ('sa_fee', models.TextField(blank=True, db_column='SA_FEE', null=True)),
                ('students', models.TextField(blank=True, db_column='STUDENTS', null=True)),
                ('notes', models.TextField(blank=True, db_column='NOTES', null=True)),
            ],
            options={
                'db_table': 'Sheet3',
                'managed': False,
            },
        ),
    ]
